[world]
topology = "Plane"
decay_factor = 0.99

[agent]
count = 20000
sensor_distance = 20.0
sensor_width = 0.6
anti_percentage = 0.0
anti_speed_factor = 0.2
wall_bounce_flip_value = true
wall_bounce_reaction = "Clip"
value = [0.6, 1.2]
speed = [1.0, 1.7]

[colors]
normal = [0.0, -1.0, -1.0]
anti = [-0.6, 0.0, -0.8]
